-- PostgreSQL schema for Zero-Intrusion Anomaly Monitoring Platform
-- Idempotent DDL: safe to run multiple times.

CREATE TABLE IF NOT EXISTS exception_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint VARCHAR(64) NOT NULL,
    app_name VARCHAR(255) NOT NULL,
    service_name VARCHAR(255),
    environment VARCHAR(255),
    host VARCHAR(255),
    pid VARCHAR(255),
    thread_name VARCHAR(255),
    class_name VARCHAR(255) NOT NULL,
    method_name VARCHAR(255) NOT NULL,
    method_signature VARCHAR(255) NOT NULL,
    arguments_snapshot TEXT,
    this_snapshot TEXT,
    exception_class VARCHAR(255) NOT NULL,
    severity VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    summary VARCHAR(512),
    message TEXT,
    stack_trace TEXT,
    top_stack_frame VARCHAR(255) NOT NULL,
    occurrence_time TIMESTAMP NOT NULL,
    trace_id VARCHAR(255),
    trace_context TEXT,
    queue_size INTEGER,
    dropped_count BIGINT,
    agent_version VARCHAR(255),
    config_version BIGINT,
    last_config_sync_at TIMESTAMP,
    last_config_sync_status VARCHAR(255),
    last_config_sync_error VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS exception_fingerprint (
    fingerprint VARCHAR(64) PRIMARY KEY,
    exception_class VARCHAR(255) NOT NULL,
    service_name VARCHAR(255),
    severity VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    summary VARCHAR(512),
    top_stack_frame VARCHAR(255) NOT NULL,
    method_signature VARCHAR(255) NOT NULL,
    occurrence_count BIGINT NOT NULL,
    first_seen TIMESTAMP NOT NULL,
    last_seen TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_analysis_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    report_status VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    summary VARCHAR(1024),
    analysis_content TEXT,
    trigger_source VARCHAR(255) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    error_message VARCHAR(1024),
    analysis_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS rule_settings (
    id VARCHAR(255) PRIMARY KEY,
    package_patterns VARCHAR(255) NOT NULL,
    deep_sampling_enabled BOOLEAN NOT NULL,
    depth_limit INTEGER NOT NULL,
    length_limit INTEGER NOT NULL,
    collection_limit INTEGER NOT NULL,
    default_sample_rate DOUBLE PRECISION NOT NULL,
    queue_capacity INTEGER NOT NULL,
    flush_interval_ms INTEGER NOT NULL,
    ai_base_url VARCHAR(255) NOT NULL,
    ai_api_key VARCHAR(2048) NOT NULL,
    ai_model VARCHAR(255) NOT NULL,
    ai_prompt_template VARCHAR(4096) NOT NULL,
    trace_keys VARCHAR(1024) NOT NULL,
    sensitive_fields VARCHAR(1024) NOT NULL,
    version BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_sync_status (
    id VARCHAR(255) PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    app_name VARCHAR(255) NOT NULL,
    environment VARCHAR(255),
    agent_version VARCHAR(255),
    target_config_version BIGINT NOT NULL,
    last_confirmed_config_version BIGINT,
    last_successful_config_version BIGINT,
    last_pulled_at TIMESTAMP,
    last_seen_at TIMESTAMP,
    last_config_sync_at TIMESTAMP,
    last_config_sync_status VARCHAR(255),
    last_config_sync_error VARCHAR(1024)
);

-- Query acceleration indexes for current service patterns.
CREATE INDEX IF NOT EXISTS idx_exception_event_occurrence_time ON exception_event (occurrence_time DESC);
CREATE INDEX IF NOT EXISTS idx_exception_event_status ON exception_event (status);
CREATE INDEX IF NOT EXISTS idx_exception_event_severity ON exception_event (severity);
CREATE INDEX IF NOT EXISTS idx_exception_event_service_name ON exception_event (service_name);
CREATE INDEX IF NOT EXISTS idx_exception_event_fingerprint ON exception_event (fingerprint);
CREATE INDEX IF NOT EXISTS idx_exception_event_fingerprint_occurrence_time ON exception_event (fingerprint, occurrence_time DESC);

CREATE INDEX IF NOT EXISTS idx_exception_fingerprint_occurrence_last_seen
    ON exception_fingerprint (occurrence_count DESC, last_seen DESC);

CREATE INDEX IF NOT EXISTS idx_agent_sync_status_service_app ON agent_sync_status (service_name, app_name);
